GET https://phonebook-fso.herokuapp.com/api/persons
###

GET https://phonebook-fso.herokuapp.com/api/persons/1

###

GET https://phonebook-fso.herokuapp.com/api/persons/abc

###

GET https://phonebook-fso.herokuapp.com/api/persons/99999999

###

POST https://phonebook-fso.herokuapp.com/api/persons
content-type: application/json

{
    "name": "test post",
    "number": "1234-5678"
}
###

DELETE https://phonebook-fso.herokuapp.com/api/persons/12376

###


GET http://localhost:3001/api/persons
###

GET http://localhost:3001/api/persons/1

###

GET http://localhost:3001/api/persons/abc

###

GET http://localhost:3001/api/persons/99999999

###
DELETE http://localhost:3001/api/persons/1

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "test post",
    "number": "1234-5678"
}